---
- hosts: webserver
  become: yes
  tasks:
    - name: install the latest version of Nginx
      yum:
        name: nginx
        state: latest
    - name: To enable and start Nginx
      service:
        name: nginx
        state: started
        
