---
- hosts: webserver
  become: yes
  tasks:
    - name: install the specific version of Apache
      yum:
        name: nginx-1.21.2
        state: present   
    - name: To enable and start Nginx
      service:
        name: nginx
        state: started
        
